name: sipkys
description: Dart counter.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  google_fonts: ^5.1.0
  collection: ^1.17.2
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.1
  uuid: ^4.0.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/icon.png"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
